Models/ErrorViewModel.cs
using System;

namespace quotingDojo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Quote.cs
using System;
using System.ComponentModel.DataAnnotations; //validations
namespace quotingDojo.Models
{
    public class Quote
    {
        [Required]
        [MinLength(2, ErrorMessage = "Must be more than 2 characters.")]
        public string Name { get; set; }

        [MaxLength(30, ErrorMessage = "Must be less than 30 characters.")]
        public string Message { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using quotingDojo.Models;

namespace quotingDojo.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/QuotesController.cs
using System.Collections.Generic;
using DbConnection;
using quotingDojo.Models;
using Microsoft.AspNetCore.Mvc;

namespace quotingDojo.Controllers
{
    public class QuotesController : Controller
    {
        [HttpGet("quotes/all")]
        public IActionResult All()
        {
            List<Dictionary<string, object>> allQuotes
                = DbConnector.Query("SELECT * FROM quotes");
            return View(allQuotes);
        }

        [HttpGet("quotes/new")]
        public IActionResult New()
        {
            return View();
        }

        [HttpPost("quotes/create")]
        public IActionResult Create(Quote newQuote)
        {

            if (ModelState.IsValid)
            {
                string insertSql = $@"
                    INSERT INTO quotes (Name, Message)
                    VALUES (
                        '{newQuote.Name}', 
                        '{newQuote.Message}')
                ";

                DbConnector.Execute(insertSql);
                return RedirectToAction("All");
            }
            else
            {
                return View("New");
            }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Quoting Dojo</h1>
</div>

Views/Quotes/All.cshtml
@model List<Dictionary<string, object>>;

    <h1 class="text-center">
        All Quotes
    </h1>
    <h5 class="text-center">
        <a href="new" class="btn btn-info">New Quote</a>
    </h5>

    @foreach (Dictionary<string, object> quote in Model)
        {
        <div class="card mx-auto mb-3" style="width: 25rem;">
            <div class="card-header">
                <h5 class="card-title">@quote["Name"]</h5>
            </div>
            <div class="card-body">
                <p class="card-text">
                    @quote["Message"]
                </p>
            </div>
        </div>
        }

Views/Quotes/New.cshtml
@model Quote

@{
    ViewData["Title"] = "Give us your quote";
}

<div class="container">
    <h1>Give us your personal quote</h1>
     <form asp-controller="Quotes" asp-action="Create">
         <div class="form-group">
             <label asp-for="Name">Name</label>
            <span class="text-danger font-weight-bold" asp-validation-for="Name"></span>
            <input class="form-control" placeholder="Your Name" asp-for="Name">
         </div>
         <div class="form-group">
             <label asp-for="Message"></label>
             <span class="text-danger font-weight-bold" asp-validation-for="Message"></span>
             <textarea class="form-control" asp-for="Message" rows="3"></textarea>
         </div>
         <button type="submit" class="btn btn-info btn-lg btn-block my-3">Submit</button>
     </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - quotingDojo</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
            asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-fallback-test-class="sr-only"
            asp-fallback-test-property="position" asp-fallback-test-value="absolute" crossorigin="anonymous"
            integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quotes" asp-action="New">New
                                Quote</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Quotes" asp-action="All">All
                                Quotes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - quotingDojo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js" asp-fallback-test="window.jQuery" crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal" crossorigin="anonymous"
            integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
            </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>

</html>